# Generated by Django 4.0.4 on 2022-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=8, verbose_name='Номер автобуса')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('departure_place', models.CharField(max_length=20, verbose_name='Точка сбора')),
                ('arrival_place', models.CharField(max_length=20, verbose_name='Место назначения')),
                ('place_cost', models.CharField(max_length=10, verbose_name='Стоимость одного места')),
                ('places', models.IntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия и имя пассажира')),
                ('ordered_buses', models.CharField(max_length=40, verbose_name='Заказанные автобусы')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
    ]
