# Generated by Django 4.0.4 on 2022-06-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOfBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название размера автобуса')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=8, verbose_name='Номер автобуса')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('departure_place', models.CharField(max_length=50, verbose_name='Точка сбора')),
                ('arrival_place', models.CharField(max_length=50, verbose_name='Место назначения')),
                ('place_cost', models.CharField(max_length=10, verbose_name='Стоимость одного места')),
                ('places', models.IntegerField(verbose_name='Количество мест')),
                ('size_of_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.sizeofbus')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
    ]
