# Generated by Django 4.0.4 on 2022-05-31 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_bus_arrival_place_alter_bus_departure_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='short_arrival_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Город назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='short_departure_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Город отправления'),
            preserve_default=False,
        ),
    ]
