# Generated by Django 4.0.4 on 2022-06-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_bus_short_arrival_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passanger',
            name='ordered_buses',
        ),
        migrations.AddField(
            model_name='passanger',
            name='ordered_buses',
            field=models.ManyToManyField(to='hello.bus'),
        ),
    ]
